---
# Configure your freshly installed software
- hosts: all
  post_tasks:
  - copy: src=dotfiles/zshrc dest=/Users/{{ ansible_user_id }}/.zshrc backup=yes
  - copy: src=dotfiles/functions dest=/Users/{{ ansible_user_id }}/.functions backup=yes
