---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: Meuk.osxc-packages
    install_cask: false         # Workaround
    brew_taps:
      - homebrew/cask-fonts
      - buo/cask-upgrade
    brew_packages:
      - git
      - zsh
      - neovim
      - iperf
      - tmux
      - wget
      - tree
      - wakeonlan
      - antigen
      - minicom
      - pass
      - pwgen
    cask_packages:
      - font-source-code-pro-for-powerline
      - iterm2
      - atom
      - spotify
      - adium
      - alfred
      - etcher
      - nextcloud
      - gpg-suite
  - role: geerlingguy.mas
    tags: mas
    mas_signin_dialog: false
    mas_installed_apps:
      - id: 866773894
        name: "Quiver"
      - id: 419330170
        name: "Moom"

- hosts: devel
  roles:
    - role: Meuk.osxc-packages
      install_cask: false       # Workaround
      brew_packages:
        - git-extras
        - git-flow
      cask_packages:
        - jetbrains-toolbox
        - gitkraken
        - virtualbox
        - vagrant
    - role: Meuk.osxc-packages
      install_cask: false       # Workaround
      tags: virtualbox
      cask_packages:
        - virtualbox
    - role: Phill93.homestead
    - role: geerlingguy.mas
      tags: mas
      mas_signin_dialog: false
      mas_installed_apps:
        - id: 497799835
          name: "Xcode"

- hosts: devel-uc
  roles:
    - role: Meuk.osxc-packages
      install_cask: false       # Workaround
      brew_taps:
        - osx-cross/avr
      brew_packages:
        - avr-gcc
        - minicom
      cask_packages:
        - arduino
