---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: Meuk.osxc-packages
    install_cask: no # Workaround
    brew_taps:
      - caskroom/fonts
    brew_packages:
      - git
      - zsh
      - neovim
      - iperf
      - tmux
      - wget
      - tree
      - wakeonlan
      - antigen
    cask_packages:
      - font-source-code-pro-for-powerline
      - iterm2
      - atom
      - spotify
      - adium
      - alfred
      - etcher
      - nextcloud
  - role: geerlingguy.mas
    mas_signin_dialog: no

- hosts: devel
  roles:
    - role: Meuk.osxc-packages
      install_cask: no # Workaround
      brew_packages:
        - git-extras
        - git-flow
      cask_packages:
        - jetbrains-toolbox
        - gitkraken
        - virtualbox
        - vagrant
    - role: Phill93.homestead
- hosts: devel-uc
  roles:
    - role: Meuk.osxc-packages
      install_cask: no # Workaround
      brew_taps:
        - osx-cross/avr
      brew_packages:
        - avr-gcc
        - minicom
      cask_packages:
        - arduino
