---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: osxc.packages
    install_cask: no # Workaround
    brew_taps:
      - caskroom/fonts
    brew_packages:
      - git
      - zsh
      - neovim
      - iperf
      - tmux
      - wget
      - tree
      - wakeonlan
    cask_packages:
      - font-source-code-pro-for-powerline
      - iterm2
      - atom
      - spotify
      - adium
      - alfred
      - etcher
- hosts: devel
  roles:
    - role: osxc.packages
      install_cask: no # Workaround
      brew_packages:
        - git-extras
      cask_packages:
        - phpstorm
        - pycharm
        - gitkraken
- hosts: devel-uc
  roles:
    - role: osxc.packages
      install_cask: no # Workaround
      brew_taps:
        - osx-cross/avr
      brew_packages:
        - avr-gcc
        - minicom
      cask_packages:
        - arduino
