---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: Meuk.osxc-packages
    install_cask: false         # Workaround
    brew_taps:
      - homebrew/cask-fonts
      - buo/cask-upgrade
      - heroku/brew
    brew_packages:
      - git
      - zsh
      - neovim
      - iperf
      - tmux
      - wget
      - tree
      - wakeonlan
      - antigen
      - minicom
      - pass
      - pwgen
      - bat
      - prettyping
      - diff-so-fancy
      - noti
      - heroku
    cask_packages:
      - font-source-code-pro-for-powerline
      - iterm2
      - spotify
      - adium
      - alfred
      - balenaetcher
      - nextcloud
      - gpg-suite-no-mail
      - omnifocus
      - presentation
      - texpad
      #- qlcolorcode Temporary
      - qlstephen
      - qlmarkdown
      - quicklook-json
      - suspicious-package
      - visual-studio-code
  - role: geerlingguy.mas
    tags: mas
    mas_signin_dialog: false
    mas_installed_apps:
      - id: 866773894
        name: "Quiver"
      - id: 419330170
        name: "Moom"
      - id: 1451685025
        name: "WireGuard"
  post_tasks:
    - git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: /Users/{{ ansible_user_id }}/.vim/bundle/Vundle.vim
    - shell: hash vim 2> /dev/null && vim +PlugInstall +qall

- hosts: devel
  roles:
    - role: Meuk.osxc-packages
      install_cask: false       # Workaround
      brew_packages:
        - git-extras
        - git-flow
      cask_packages:
        - jetbrains-toolbox
        - gitkraken
        - vagrant
        - insomnia
        - xca
        - sequel-pro
        #- mqttfx Temporary
    - role: Meuk.osxc-packages
      install_cask: false       # Workaround
      tags: virtualbox
      cask_packages:
        - virtualbox
    - role: Phill93.homestead
    - role: geerlingguy.mas
      tags: mas
      mas_signin_dialog: false
      mas_installed_apps:
        - id: 497799835
          name: "Xcode"

- hosts: devel-uc
  roles:
    - role: Meuk.osxc-packages
      install_cask: false       # Workaround
      brew_taps:
        - osx-cross/avr
        - homebrew/cask-drivers
      brew_packages:
        - avr-gcc
        - minicom
      cask_packages:
        - arduino
        - ftdi-vcp-driver
