---
# Ansible Galaxy Requirements
- name: Meuk.common-env
  src: https://github.com/Meuk/osxc-common-env
  scm: git
  version: master

- name: Meuk.homebrew
  src: https://github.com/itiut/homebrew
  version: master

- name: Meuk.packages
  src: https://github.com/Meuk/osxc-packages.git
  version: master

- name: Meuk.repository
  src: https://github.com/sgerogia/osxc-repository
  version: master
