---
# Ansible Galaxy Requirements
- name: common-env
  src: https://github.com/Meuk/osxc-common-env
  scm: git
  version: master

- name: homebrew
  src: https://github.com/itiut/homebrew
  version: master

- name: packages
  src: https://github.com/Meuk/osxc-packages.git
  version: master

- name: repository
  src: https://github.com/sgerogia/osxc-repository
  version: master
