---

# Homebrew
homebrew_upgrade_all_packages: true
homebrew_installed_packages:
  - age
  - antigen
  - argocd
  - assh
  - bat
  - chezmoi
  - diff-so-fancy
  - git
  - git-extras
  - git-flow
  - iperf
  - kubernetes-cli
  - kustomize
  - mqtt-cli
  - neovim
  - noti
  - pass
  - poetry
  - prettyping
  - pwgen
  - sops
  - telnet
  - tio
  - tmux
  - tree
  - watch
  - wget
  - zsh
homebrew_cask_apps:
  - aldente
  - alfred
  - bartender
  - font-jetbrains-mono
  - gpg-suite-no-mail
  - iterm2
  - jetbrains-toolbox
  - keepingyouawake
  - logitech-options
  - monitorcontrol
  - nextcloud
  - oversight
  - presentation
  - spotify
  - vagrant
  - viscosity
  - visual-studio-code
  - xquartz
homebrew_taps:
  - hivemq/mqtt-cli

# Mac App Store (MAS)
mas_signin_dialog: false
mas_upgrade_all_apps: true
mas_installed_apps:
  - id: 1440147259
    name: AdGuard for Safari
  - id: 1616831348
    name: Affinity Designer 2
  - id: 1616822987
    name: Affinity Photo 2
  - id: 1606941598
    name: Affinity Publisher 2
  - id: 1035236694
    name: Commander One
  - id: 409183694
    name: Keynote
  - id: 441258766
    name: Magnet
  - id: 409203825
    name: Numbers
  - id: 818195014
    name: OX Drive
  - id: 409201541
    name: Pages
  - id: 429449079
    name: Patterns
  - id: 1276493162
    name: reMarkable
  - id: 1475387142
    name: Tailscale
  - id: 747648890
    name: Telegram
  - id: 1295203466
    name: Windows App
mas_uninstalled_apps:
  - id: 40891434
    name: iMovie
  - id: 682658836
    name: GarageBand
